apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-docker
  labels:
    app: echo-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-docker
  template:
    metadata:
      labels:
        app: echo-docker
    spec:
      containers:
      - name: echo-docker
        image: echo-docker:1.0.0

---
apiVersion: v1
kind: Service
metadata:
  name: echo-docker
spec:
  selector:
    app: echo-docker
